#!/bin/bash
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_72.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_73.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_74.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_75.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_76.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_77.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_78.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_79.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_80.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_81.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_82.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_83.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_84.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_85.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_86.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_87.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_88.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_89.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_90.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_91.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_92.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_93.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_94.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_95.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_96.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_97.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_98.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_99.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_100.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_101.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_102.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_103.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_104.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_105.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_106.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_107.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_108.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_109.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_110.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_111.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_112.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_113.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_114.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_115.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_116.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_117.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_118.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_119.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_120.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_121.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_122.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_123.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_124.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_125.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_126.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_127.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_128.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_129.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_130.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_131.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_132.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_133.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_134.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_135.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_136.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_137.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_138.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_139.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_140.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_141.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_142.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_143.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_144.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_145.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_146.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_147.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_148.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_149.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_150.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_151.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_152.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_153.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_154.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_155.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_156.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_157.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_158.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_159.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_160.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_161.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_162.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_163.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_164.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_165.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_166.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_167.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_168.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_169.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_170.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_171.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_172.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_173.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_174.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_175.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_176.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_177.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_178.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_179.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_180.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_181.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_182.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_183.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_184.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_185.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_186.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_187.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_188.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_189.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_190.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_191.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_192.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_193.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_194.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_195.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_196.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_197.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_198.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_199.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_200.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_201.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_202.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_203.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_204.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_205.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_206.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_207.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_208.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_209.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_210.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_211.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_212.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_213.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_214.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_215.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_216.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_217.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_218.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_219.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_220.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_221.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_222.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_223.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_224.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_225.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_226.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_227.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_228.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_229.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_230.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_231.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_232.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_233.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_234.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_235.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_236.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_237.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_238.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_239.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_240.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_241.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_242.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_243.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_244.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_245.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_246.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_247.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_248.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_249.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_250.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_251.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_252.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_253.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_254.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_255.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_256.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_257.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_258.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_259.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_260.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_261.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_262.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_TTToSemiLeptonic_2018_263.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_2.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_3.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_4.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_5.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_6.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_7.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_8.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_9.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_10.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_11.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_12.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_13.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_14.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_15.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_16.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_17.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_18.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_19.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_20.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_21.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WJetsToQQ_2018_22.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWTo4Q_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWTo4Q_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWW_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWW_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWW_2018_2.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWW_2018_3.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_2.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_3.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_4.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_5.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_6.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_7.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_8.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_9.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WWZ_2018_10.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_2.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_3.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_4.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_5.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_6.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_7.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_8.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_9.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_10.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_WZZ_2018_11.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_2.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_3.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_4.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_5.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_6.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_7.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_8.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_9.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_10.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_11.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_12.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_13.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_14.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_15.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_16.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_17.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_18.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_19.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_20.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_21.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_22.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_23.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_24.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_25.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_26.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_27.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_28.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_29.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZJetsToQQ_2018_30.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZTo4Q_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_0.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_1.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_2.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_3.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_4.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_5.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_6.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_7.sh
sbatch /users/mstamenk/hhh-analysis-framework/spanet-inference//condor-slurm//jobs/job_ZZZ_2018_8.sh
