#!/bin/bash
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_1_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_10_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_100_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_101_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_102_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_103_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_104_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_105_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_106_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_107_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_107_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_108_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_108_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_109_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_11_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_110_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_112_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_113_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_114_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_114_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_115_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_116_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_117_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_117_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_118_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_119_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_119_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_12_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_120_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_121_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_121_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_123_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_123_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_124_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_124_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_125_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_125_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_126_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_126_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_127_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_127_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_128_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_128_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_129_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_13_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_13_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_130_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_130_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_131_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_131_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_132_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_132_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_133_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_133_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_134_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_134_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_135_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_135_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_136_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_138_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_139_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_139_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_14_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_14_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_141_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_142_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_142_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_143_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_143_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_144_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_145_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_146_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_147_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_148_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_148_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_149_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_15_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_150_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_150_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_151_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_152_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_152_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_153_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_153_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_154_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_155_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_156_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_156_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_157_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_157_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_158_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_158_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_159_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_159_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_16_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_160_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_161_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_162_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_163_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_163_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_164_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_165_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_165_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_166_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_167_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_167_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_168_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_169_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_169_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_17_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_170_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_170_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_171_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_172_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_172_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_173_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_173_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_174_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_175_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_175_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_176_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_176_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_177_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_178_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_178_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_179_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_18_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_18_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_180_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_180_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_181_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_182_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_182_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_183_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_184_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_19_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_19_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_2-8_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_2-9_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_2_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_20_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_20_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_21_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_22_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_22_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_23_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_24_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_25_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_27_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_27_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_28_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_29_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_3_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_3_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_30_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_31_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_31_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_32_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_33_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_33_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_34_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_34_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_35_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_35_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_36_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_36_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_37_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_37_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_38_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_38_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_39_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_39_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_4_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_40_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_40_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_41_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_41_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_42_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_42_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_43_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_48_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_49_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_5_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_50_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_50_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_51_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_52_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_53_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_54_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_55_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_55_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_56_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_57_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_58_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_58_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_59_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_6_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_60_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_61_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_62_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_63_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_63_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_64_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_65_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_66_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_67_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_68_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_69_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_7_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_70_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_70_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_71_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_72_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_73_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_73_2018_1.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_74_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_75_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_76_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_77_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_78_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_79_2018_0.sh
sbatch /eos/user/x/xgeng/workspace/HHH/CMSSW_12_5_2/src/hhh-analysis-framework/spanet-inference//condor-xinyue//jobs/job_nano_79_2018_1.sh
